_target_: src.trainer.sdxl_trainers.PhotomakerLoraTrainer
device_tensors: ["pixel_values"]
cfg_step: 10
masked_loss_step: 2
log_step: 50
n_epochs: 10000
epoch_len: 1000
resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
from_pretrained: null
save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
save_dir: "saved"
seed: 0
max_grad_norm: null