name: photomaker_NS
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.18
  - python_abi=3.10
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.10.1
      - antlr4-python3-runtime==4.9.3
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - comet-ml==3.53.1
      - configobj==5.0.9
      - contourpy==1.3.2
      - cycler==0.12.1
      - dulwich==0.24.2
      - einops==0.8.1
      - everett==3.1.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - idna==3.10
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mediapipe==0.10.18
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - narwhals==2.7.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnx==1.19.0
      - opencv-contrib-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==10.2.0
      - plotly==6.3.1
      - polars==1.38.0
      - polars-runtime-32==1.38.0
      - protobuf==4.25.8
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - semantic-version==2.10.0
      - sentencepiece==0.1.96
      - simplejson==3.20.2
      - sounddevice==0.5.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.2.0
      - tzdata==2025.2
      - ultralytics==8.4.11
      - ultralytics-thop==2.0.18
      - urllib3==2.5.0
      - wrapt==1.17.3
      - wurlitzer==3.1.1
prefix: /home/dnbobkov/.conda/envs/photomaker_NS
